### PR TITLE
examples: Add an XDP example

### PR DESCRIPTION
**Pull request by dave-tucker**
This PR adds an example that shows:

1. How to create a simple XDP program that simply increments a counter, stored in a map.
1. How to write a userspace program that loads the program and reads the data in the map.

The BPF program must be compiled using:
`cargo +nightly build --examples -Z build-std=core --target=bpfel-unknown-none`

The userspace example can be run using:
`cargo run --example xdp -- <your-interface-name>`

### CODE REVIEW

**Comment by dave-tucker** [comment]
Running the program currently fails with `thread 'main' panicked at 'attempt to subtract with overflow', aya/src/obj/relocation.rs:288:17`

**Comment by alessandrod** [comment]
I think examples should go under a new `aya-examples` package. I actually had one at some point. As for the relocation issue, I'll take a look!

**Comment by dave-tucker** [comment]
@alessandrod thanks for the feedback. I've re-orgainzed this now.
I also noted something curious in the `// FIXME` comment.

```rust
// FIXME: We should be able to share structs between BPF and Userspace.
// However, the Array<MapRef, Value> requires that Value implements the aya::Pod trait
// This can't be done from `bpf/src/xdp/mod.rs` as the aya paclage is not no_std
// It can't be done from here because:
// error[E0117]: only traits defined in the current crate can be implemented for arbitrary types
#[derive(Copy, Clone)]
#[repr(C)]
pub struct XdpData {
    pub packet_count : u32,
}
unsafe impl aya::Pod for XdpData {}
```

Wondering if I've approached this wrong, or maybe we can drop the requirement of the Pod trait and/or relocate it somewhere `no_std` so structs can be shared between eBPF and userspace code.

**Comment by alessandrod** [comment]
> @alessandrod thanks for the feedback. I've re-orgainzed this now.
> I also noted something curious in the `// FIXME` comment.
> 
> ```rust
> // FIXME: We should be able to share structs between BPF and Userspace.
> // However, the Array<MapRef, Value> requires that Value implements the aya::Pod trait
> // This can't be done from `bpf/src/xdp/mod.rs` as the aya paclage is not no_std
> // It can't be done from here because:
> // error[E0117]: only traits defined in the current crate can be implemented for arbitrary types
> #[derive(Copy, Clone)]
> #[repr(C)]
> pub struct XdpData {
>     pub packet_count : u32,
> }
> unsafe impl aya::Pod for XdpData {}
> ```
> 
> Wondering if I've approached this wrong, or maybe we can drop the requirement of the Pod trait and/or relocate it somewhere `no_std` so structs can be shared between eBPF and userspace code.

The way I've done this is having two features, "user" and "kernel" in the bpf crate. Then have userspace activate the user feature with:

```
bpf = { path = "./bpf", default-features = false, features = ["user"] }
```

and in the bpf crate implement `aya::Pod` with

```
[cfg(feature = "user")]
pub mod user {
    use super::*;

    unsafe impl aya::Pod for SharedStruct {}
}
```

**Comment by dave-tucker** [comment]
@alessandrod getting closer now :+1: 

- Examples are in their own directory
- Adjusted the module layout as suggested above to add a `user` feature to the `bpf` crate for shared data structures.
- I've added `cargo xtask examples` which will compile the bpf examples and userspace programs
- I've added a section to the readme to show how to use the examples

The example still isn't working correctly though.
Now there isn't a relocation error, but instead `Bpf::load_file` appears to time out, and I don't get an error on the console.
I'll keep debugging and see if I can figure out what's going on

**Comment by dave-tucker** [comment]
Ok, this feels mostly complete now and ready for review.
I've put a workaround for #34 in place.
The initial relocation problem was actually quite funny actually... as it turns out it was the overflow checks in the Cargo dev profile :joy:

**Comment by dave-tucker** [comment]
Going to close this one for now since the book example is better.

**Pull request closed without merging**
